# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sNLAN5Blqu9C3uBKHqSVlMNOfANJGtW7
"""

nums=[2,4,6,8,10]

square=[i**2 for i in nums]
print("Square of nums is :",square)

cube=[i**3 for i in nums]
print("Cube of nums is :",cube)

